/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jokyxray_ndksimple_AccessMethod */

#ifndef _Included_com_jokyxray_ndksimple_AccessMethod
#define _Included_com_jokyxray_ndksimple_AccessMethod
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jokyxray_ndksimple_AccessMethod
 * Method:    callStaticMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jokyxray_ndksimple_AccessMethod_callStaticMethod
        (JNIEnv *, jclass);

/*
 * Class:     com_jokyxray_ndksimple_AccessMethod
 * Method:    callInstanceMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jokyxray_ndksimple_AccessMethod_callInstanceMethod
        (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
